name: dumbdumb_flutter_app
description: My dumbdumb Flutter app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  provider: ^6.1.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # System/Structure
  go_router: ^15.2.3
  recaptcha_enterprise_flutter: ^18.7.1

  # Device Info
  device_info_plus: ^11.5.0
  package_info_plus: ^8.3.0
  store_redirect: ^2.0.4
  permission_handler: ^12.0.0+1
  jailbreak_root_detection: ^1.1.6

  # Image
  image_picker: ^1.1.2
  image_picker_android: ^0.8.12+23
  image_picker_platform_interface: ^2.10.1
  flutter_image_compress: ^2.4.0

  # Data
  dio: ^5.8.0+1
  shared_preferences: ^2.5.3
  file: ^7.0.1

  # Firebase
  firebase_core: ^3.14.0
  firebase_analytics: ^11.5.0
  firebase_messaging: ^15.2.7
  firebase_crashlytics: ^4.3.7
  firebase_remote_config: ^5.4.5

  # Push Notification
  flutter_local_notifications: ^19.2.1
  cached_network_image: ^3.4.1
  photo_view: ^0.15.0
  flutter_easyloading: ^3.0.5
  fluttertoast: ^8.2.12
  version: ^3.0.2
  collection: ^1.19.1
  url_launcher: ^6.3.1
  file_picker: ^10.2.0
  path: ^1.9.1
  adaptive_widgets_flutter: ^0.1.5
  internet_connection_checker_plus: ^2.7.2
  infinite_scroll_pagination: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  cobertura: ^1.0.5

flutter:
  uses-material-design: true
  generate: true
flutter_intl:
  enabled: true
